# Generated by Django 5.1.6 on 2025-03-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int1', models.IntegerField()),
                ('float1', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('roomnr', models.IntegerField()),
                ('ll_pieces', models.JSONField()),
            ],
        ),
    ]
