# Generated by Django 5.1.6 on 2025-03-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_board_game_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_state',
            old_name='ll_pieces',
            new_name='state_player',
        ),
    ]
