# Generated by Django 5.1.6 on 2025-03-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_ll_pieces_game_state_state_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_state',
            old_name='state_player',
            new_name='state_players',
        ),
    ]
