# Generated by Django 5.1.6 on 2025-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_state_player_game_state_state_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_state',
            name='roomnr',
            field=models.IntegerField(unique=True),
        ),
    ]
